import Head from "next/head";
import React from "react";
import { SendEthereum } from "../../components/SendEthereum";
import { Dashboard } from "../../containers";

const DashboardPage = () => {
  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard />
      <SendEthereum></SendEthereum>
    </div>
  );
};

export default DashboardPage;
