import Head from "next/head";
import React from "react";
import { Dashboard } from "../../containers";
import styles from "../../styles/Dashboard.module.css";
const DashboardPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard />
    </div>
  );
};

export default DashboardPage;
