import Head from "next/head";
import { Button } from "../components";

import { MetamaskLogin } from "../components/MetamaskLogin";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button onClick={() => console.log("click me")} text="click me" />
      <MetamaskLogin></MetamaskLogin>
    </div>
  );
}
