import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/Landing.module.css";
export default function Home() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome to daily wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.buttonContainer}>
        <button
          className={styles.button}
          onClick={() => router.push("/sign-in")}
          type="metamask"
        >
          Get started
        </button>
      </div>
    </div>
  );
}
